data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  num_aokvqa_samples: 1000
  num_scienceqa_samples: 500
  train_split: 0.9
  val_split: 0.1
  random_seed: 42
  image_format: "jpg"
  max_image_size: 1024
